theme: minima
title: Thoughts on math and computer science
author: Anders
description: "This blog will hopefully come to contain posts within math and computer science which I myself 
  would have liked to read. In other words it is in some sense intended at a younger version of myself and containing
  the posts I woudl have liked to read." 
